module.exports = {
  env: {
    AWS_APPSYNC_URL: process.env.AWS_APPSYNC_URL,
    AWS_APPSYNC_REGION: process.env.AWS_APPSYNC_REGION,
    AWS_APPSYNC_API_KEY: process.env.AWS_APPSYNC_API_KEY,

    GOOGLE_ANALYTICS_TRACKING_CODE: process.env.GOOGLE_ANALYTICS_TRACKING_CODE
  }
}