const DISABLE_DYNAMIC_HEADER = 'DISABLE_DYNAMIC_HEADER';
const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU';
const OPEN_MOBILE_MENU = 'OPEN_MOBILE_MENU';
const CLOSE_MOBILE_MENU = 'CLOSE_MOBILE_MENU';

export default {
  DISABLE_DYNAMIC_HEADER,
  TOGGLE_MOBILE_MENU,
  OPEN_MOBILE_MENU,
  CLOSE_MOBILE_MENU
}

export interface State {
  mobileMenuVisible: boolean
}