name: PR

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy - Vercel
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v1
        id: submodule-cache
        with:
          path: src/shared/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('src/shared/yarn.lock') }}
      - name: Yarn Install
        if: steps.cache.outputs.cache-hit != 'true' || steps.submodule-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-org-id: ${{ secrets.ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} #Required